{
 "title": "Path Statistics",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Network Path Efficiency (average over last 5 min)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"raw_data_export\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"netflow\")\n  |> filter(fn: (r) => r[\"aggregator\"] == \"0\")\n  |> filter(fn: (r) => r[\"flags\"] == \"0\")\n  |> filter(fn: (r) => r[\"_field\"] == \"aggregate\")\n  |> group(columns: [\"flow_label\", \"src\"])\n  |> group()\n  |> aggregateWindow(every: 5m, fn: mean)"
    }
   ]
  },
  {
   "title": "PEI Distribution",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"raw_data_export\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"netflow\")\n  |> filter(fn: (r) => r[\"aggregator\"] == \"0\")\n  |> filter(fn: (r) => r[\"flags\"] == \"0\")\n  |> filter(fn: (r) => r[\"_field\"] == \"aggregate\")\n  |> group(columns: [\"flow_label\", \"src\"])\n  |> aggregateWindow(every: inf, fn: sum)\n  |> group()\n  |> filter(fn: (r) => r[\"_value\"] != 0)\n  |> unique(column: \"flow_label\")"
    }
   ]
  },
  {
   "title": "Current Path Statistic from Host to Host",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"raw_data_export\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"netflow\")\n  |> filter(fn: (r) => r[\"flags\"] == \"0\")\n  |> filter(fn: (r) => r[\"_field\"] == \"aggregate\")\n  |> group(columns: [\"source_ipv6\", \"destination_ipv6\"])\n  |> map(fn: (r) => ({ r with path: r.node_01 + \"-\" + r.node_02 + \"-\" + r.node_03 + \"-\" + r.node_04}))\n  |> keep(columns: [\"_time\", \"source_ipv6\", \"destination_ipv6\", \"path\", \"_value\"])\n  |> truncateTimeColumn(unit: 1s)\n  |> map(fn: (r) => ({ r with timestamp: r._time }))\n  |> aggregateWindow(every: inf, fn: last)\n  |> group()\n  |> filter(fn: (r) => r[\"_value\"] != 0)\n  |> drop(columns: [\"_time\", \"_start\", \"_stop\", \"_value\"])\n\n  |> map(fn: (r) => ({ r with source_ipv6: if r.source_ipv6 == \"2a04:f340:0000:0000:0000:0000:0000:000a\" then \"h01\" else r.source_ipv6 }))\n  |> map(fn: (r) => ({ r with destination_ipv6: if r.destination_ipv6 == \"2a04:f340:0000:0000:0000:0000:0000:000a\" then \"h01\" else r.destination_ipv6 }))\n\n  |> map(fn: (r) => ({ r with source_ipv6: if r.source_ipv6 == \"2a00:10c0:0000:0000:0000:0000:0000:000a\" then \"h02\" else r.source_ipv6 }))\n  |> map(fn: (r) => ({ r with destination_ipv6: if r.destination_ipv6 == \"2a00:10c0:0000:0000:0000:0000:0000:000a\" then \"h02\" else r.destination_ipv6 }))\n\n  |> map(fn: (r) => ({ r with source_ipv6: if r.source_ipv6 == \"2001:067c:0470:0000:0000:0000:0000:000a\" then \"h03\" else r.source_ipv6 }))\n  |> map(fn: (r) => ({ r with destination_ipv6: if r.destination_ipv6 == \"2001:067c:0470:0000:0000:0000:0000:000a\" then \"h03\" else r.destination_ipv6 }))\n\n  |> map(fn: (r) => ({ r with source_ipv6: if r.source_ipv6 == \"2a00:0c38:0000:0000:0000:0000:0000:000a\" then \"h04\" else r.source_ipv6 }))\n  |> map(fn: (r) => ({ r with destination_ipv6: if r.destination_ipv6 == \"2a00:0c38:0000:0000:0000:0000:0000:000a\" then \"h04\" else r.destination_ipv6 }))\n\n  |> map(fn: (r) => ({ r with source_ipv6: if r.source_ipv6 == \"2a02:02d8:0000:0000:0000:0000:0000:000a\" then \"h05\" else r.source_ipv6 }))\n  |> map(fn: (r) => ({ r with destination_ipv6: if r.destination_ipv6 == \"2a02:02d8:0000:0000:0000:0000:0000:000a\" then \"h05\" else r.destination_ipv6 }))\n\n  |> map(fn: (r) => ({ r with source_ipv6: if r.source_ipv6 == \"2607:5d00:0000:0000:0000:0000:0000:000a\" then \"h06\" else r.source_ipv6 }))\n  |> map(fn: (r) => ({ r with destination_ipv6: if r.destination_ipv6 == \"2607:5d00:0000:0000:0000:0000:0000:000a\" then \"h06\" else r.destination_ipv6 }))\n\n  |> map(fn: (r) => ({ r with source_ipv6: if r.source_ipv6 == \"2a05:ff80:0000:0000:0000:0000:0000:000a\" then \"h07\" else r.source_ipv6 }))\n  |> map(fn: (r) => ({ r with destination_ipv6: if r.destination_ipv6 == \"2a05:ff80:0000:0000:0000:0000:0000:000a\" then \"h07\" else r.destination_ipv6 }))\n\n  |> map(fn: (r) => ({ r with source_ipv6: if r.source_ipv6 == \"2a0a:de00:0000:0000:0000:0000:0000:000a\" then \"h08\" else r.source_ipv6 }))\n  |> map(fn: (r) => ({ r with destination_ipv6: if r.destination_ipv6 == \"2a0a:de00:0000:0000:0000:0000:0000:000a\" then \"h08\" else r.destination_ipv6 }))\n\n  |> map(fn: (r) => ({ r with source_ipv6: if r.source_ipv6 == \"2001:0678:0274:0000:0000:0000:0000:000a\" then \"h09\" else r.source_ipv6 }))\n  |> map(fn: (r) => ({ r with destination_ipv6: if r.destination_ipv6 == \"2001:0678:0274:0000:0000:0000:0000:000a\" then \"h09\" else r.destination_ipv6 }))\n\n  |> map(fn: (r) => ({ r with source_ipv6: if r.source_ipv6 == \"2001:0678:00e0:0000:0000:0000:0000:000a\" then \"h10\" else r.source_ipv6 }))\n  |> map(fn: (r) => ({ r with destination_ipv6: if r.destination_ipv6 == \"2001:0678:00e0:0000:0000:0000:0000:000a\" then \"h10\" else r.destination_ipv6 }))\n\n  |> map(fn: (r) => ({ r with source_ipv6: if r.source_ipv6 == \"2001:0678:07f0:0000:0000:0000:0000:000a\" then \"h11\" else r.source_ipv6 }))\n  |> map(fn: (r) => ({ r with destination_ipv6: if r.destination_ipv6 == \"2001:0678:07f0:0000:0000:0000:0000:000a\" then \"h11\" else r.destination_ipv6 }))"
    }
   ]
  },
  {
   "title": "PEI Statistics",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"raw_data_export\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"netflow\")\n  |> filter(fn: (r) => r[\"aggregator\"] == \"0\")\n  |> filter(fn: (r) => r[\"flags\"] == \"0\")\n  |> filter(fn: (r) => r[\"_field\"] == \"aggregate\")\n  |> group(columns: [\"node_01\", \"node_02\", \"node_03\", \"node_04\"])\n  |> map(fn: (r) => ({ r with path: r.node_01 + \"-\" + r.node_02 + \"-\" + r.node_03 + \"-\" + r.node_04}))\n  |> keep(columns: [\"_time\", \"path\", \"_value\"])\n  |> truncateTimeColumn(unit: 1s)\n  |> map(fn: (r) => ({ r with timestamp: r._time }))\n  |> group(columns: [\"path\"])\n  |> aggregateWindow(every: inf, fn: last)\n  |> drop(columns: [\"_time\", \"_start\", \"_stop\"])\n  |> filter(fn: (r) => r[\"_value\"] != 0)\n  |> group()"
    }
   ]
  },
  {
   "title": "Path Efficiency over Time",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "query": "from(bucket: \"raw_data_export\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"netflow\")\n  |> filter(fn: (r) => r[\"aggregator\"] == \"0\")\n  |> filter(fn: (r) => r[\"flags\"] == \"0\")\n  |> filter(fn: (r) => r[\"_field\"] == \"aggregate\")\n  |> group(columns: [\"node_01\", \"node_02\", \"node_03\", \"node_04\"])\n  |> pivot(rowKey: [\"_time\", \"node_01\", \"node_02\", \"node_03\", \"node_04\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> map(fn: (r) => ({ r with _value: r.aggregate }))\n  |> drop(columns: [\"aggregate\"])\n  |> map(fn: (r) => ({ r with path: r.node_01 + \"-\" + r.node_02 + \"-\" + r.node_03 + \"-\" + r.node_04}))\n  |> group(columns: [\"path\"])\n  |> aggregateWindow(every: 5m, fn: mean)\n  |> filter(fn: (r) => r[\"_value\"] != 0)"
    }
   ]
  }
 ]
}