{
 "title": "Simulation Network Statistics",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Aggregator Used for Percentage of Packets",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"aggregated_data_export\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"netflow\")\n  |> filter(fn: (r) => r[\"type_5053\"] == \"0\" and r[\"type_5054\"] == \"0\" and r[\"type_5055\"] == \"0\" and r[\"type_5056\"] == \"0\")\n  |> filter(fn: (r) => r[\"_field\"] == \"in_packets\")\n  |> filter(fn: (r) => r[\"type_5052\"] == \"0x00\" or r[\"type_5052\"] == \"0x01\" or r[\"type_5052\"] == \"0x02\")\n  |> group(columns: [\"type_5052\"])\n  |> aggregateWindow(every: inf, fn: sum)\n  |> filter(fn: (r) => r[\"_value\"] != 0)"
    }
   ]
  },
  {
   "title": "Number of Packets per Flow Distribution",
   "type": "histogram",
   "gridPos": { "h": 11, "w": 17, "x": 7, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"aggregated_data_export\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"netflow\")\n  |> filter(fn: (r) => r[\"type_5053\"] == \"0\" and r[\"type_5054\"] == \"0\" and r[\"type_5055\"] == \"0\" and r[\"type_5056\"] == \"0\")\n  |> filter(fn: (r) => r[\"_field\"] == \"in_packets\")\n  |> group(columns: [\"flow_label\", \"src\"])\n  |> aggregateWindow(every: inf, fn: sum)\n  |> group()\n  |> filter(fn: (r) => r[\"_value\"] != 0)\n  |> unique(column: \"flow_label\")"
    }
   ]
  },
  {
   "title": "Number of Packets by Destination (Last 5min Average)",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "query": "from(bucket: \"aggregated_data_export\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"netflow\")\n  |> filter(fn: (r) => r[\"type_5053\"] == \"0\" and r[\"type_5054\"] == \"0\" and r[\"type_5055\"] == \"0\" and r[\"type_5056\"] == \"0\")\n  |> filter(fn: (r) => r[\"_field\"] == \"in_packets\")\n  |> group(columns: [\"dst\"])\n  |> aggregateWindow(every: 5m, fn: sum)"
    }
   ]
  },
  {
   "title": "Number of Packets with Unsupported Aggregators",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"aggregated_data_export\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"netflow\")\n  |> filter(fn: (r) => r[\"type_5053\"] != \"0\")\n  |> filter(fn: (r) => r[\"_field\"] == \"type_5051\")\n  |> keep(columns: [\"_time\", \"flow_label\", \"type_5052\", \"type_5053\"])\n  |> group(columns: [\"flow_label\", \"src\", \"dst\"])\n  |> map(fn: (r) => ({ r with _value: int(v: r.type_5053) }))\n  |> aggregateWindow(every: inf, fn: sum)\n  |> drop(columns: [\"flow_label\"])\n  |> aggregateWindow(every: inf, fn: sum)\n  |> filter(fn: (r) => r[\"_value\"] != 0)"
    }
   ]
  },
  {
   "title": "Number of Packets per Flow with Unsupported Aggregators",
   "type": "table",
   "gridPos": { "h": 7, "w": 17, "x": 7, "y": 27 },
   "targets": [
    {
     "query": "from(bucket: \"aggregated_data_export\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"netflow\")\n  |> filter(fn: (r) => r[\"type_5053\"] != \"0\")\n  |> filter(fn: (r) => r[\"_field\"] == \"type_5051\")\n  |> keep(columns: [\"_time\", \"flow_label\", \"src\", \"dst\", \"type_5052\", \"type_5053\"])\n  |> map(fn: (r) => ({ r with _value: int(v: r.type_5053) }))\n  |> group(columns: [\"flow_label\"])\n  |> truncateTimeColumn(unit: 1s)\n  |> map(fn: (r) => ({ r with timestamp: r._time }))\n  |> group(columns: [\"flow_label\", \"src\", \"dst\", \"timestamp\"])\n  |> aggregateWindow(every: inf, fn: sum)\n  |> drop(columns: [\"_time\", \"_start\", \"_stop\", \"type_5053\"])\n  |> filter(fn: (r) => r[\"_value\"] != 0)\n  |> group()\n\n  |> map(fn: (r) => ({ r with src: if r.src == \"2a04:f340::a\" then \"h01\" else r.src }))\n  |> map(fn: (r) => ({ r with dst: if r.dst == \"2a04:f340::a\" then \"h01\" else r.dst }))\n\n  |> map(fn: (r) => ({ r with src: if r.src == \"2a00:10c0::a\" then \"h02\" else r.src }))\n  |> map(fn: (r) => ({ r with dst: if r.dst == \"2a00:10c0::a\" then \"h02\" else r.dst }))\n\n  |> map(fn: (r) => ({ r with src: if r.src == \"2001:67c:470::a\" then \"h03\" else r.src }))\n  |> map(fn: (r) => ({ r with dst: if r.dst == \"2001:67c:470::a\" then \"h03\" else r.dst }))\n\n  |> map(fn: (r) => ({ r with src: if r.src == \"2a00:c38::a\" then \"h04\" else r.src }))\n  |> map(fn: (r) => ({ r with dst: if r.dst == \"2a00:c38::a\" then \"h04\" else r.dst }))\n\n  |> map(fn: (r) => ({ r with src: if r.src == \"2a02:2d8::a\" then \"h05\" else r.src }))\n  |> map(fn: (r) => ({ r with dst: if r.dst == \"2a02:2d8::a\" then \"h05\" else r.dst }))\n\n  |> map(fn: (r) => ({ r with src: if r.src == \"2607:5d00::a\" then \"h06\" else r.src }))\n  |> map(fn: (r) => ({ r with dst: if r.dst == \"2607:5d00::a\" then \"h06\" else r.dst }))\n\n  |> map(fn: (r) => ({ r with src: if r.src == \"2a05:ff80::a\" then \"h07\" else r.src }))\n  |> map(fn: (r) => ({ r with dst: if r.dst == \"2a05:ff80::a\" then \"h07\" else r.dst }))\n\n  |> map(fn: (r) => ({ r with src: if r.src == \"2a0a:de00::a\" then \"h08\" else r.src }))\n  |> map(fn: (r) => ({ r with dst: if r.dst == \"2a0a:de00::a\" then \"h08\" else r.dst }))\n\n  |> map(fn: (r) => ({ r with src: if r.src == \"2001:678:274::a\" then \"h09\" else r.src }))\n  |> map(fn: (r) => ({ r with dst: if r.dst == \"2001:678:274::a\" then \"h09\" else r.dst }))\n\n  |> map(fn: (r) => ({ r with src: if r.src == \"2001:678:e0::a\" then \"h10\" else r.src }))\n  |> map(fn: (r) => ({ r with dst: if r.dst == \"2001:678:e0::a\" then \"h10\" else r.dst }))\n\n  |> map(fn: (r) => ({ r with src: if r.src == \"2001:678:7f0::a\" then \"h11\" else r.src }))\n  |> map(fn: (r) => ({ r with dst: if r.dst == \"2001:678:7f0::a\" then \"h11\" else r.dst }))"
    }
   ]
  },
  {
   "title": "Number of Packets with Unsupported Data Parameter",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"aggregated_data_export\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"netflow\")\n  |> filter(fn: (r) => r[\"type_5054\"] != \"0\")\n  |> filter(fn: (r) => r[\"_field\"] == \"type_5051\")\n  |> keep(columns: [\"_time\", \"flow_label\", \"type_5052\", \"type_5054\"])\n  |> group(columns: [\"flow_label\", \"src\", \"dst\"])\n  |> map(fn: (r) => ({ r with _value: int(v: r.type_5054) }))\n  |> aggregateWindow(every: inf, fn: sum)\n  |> drop(columns: [\"flow_label\"])\n  |> aggregateWindow(every: inf, fn: sum)\n  |> filter(fn: (r) => r[\"_value\"] != 0)"
    }
   ]
  },
  {
   "title": "Number of Packets per Flow with Unsupported Data Parameter",
   "type": "table",
   "gridPos": { "h": 7, "w": 17, "x": 7, "y": 34 },
   "targets": [
    {
     "query": "from(bucket: \"aggregated_data_export\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"netflow\")\n  |> filter(fn: (r) => r[\"type_5054\"] != \"0\")\n  |> filter(fn: (r) => r[\"_field\"] == \"type_5051\")\n  |> keep(columns: [\"_time\", \"flow_label\", \"src\", \"dst\", \"type_5052\", \"type_5054\"])\n  |> map(fn: (r) => ({ r with _value: int(v: r.type_5054) }))\n  |> group(columns: [\"flow_label\"])\n  |> truncateTimeColumn(unit: 1s)\n  |> map(fn: (r) => ({ r with timestamp: r._time }))\n  |> group(columns: [\"flow_label\", \"src\", \"dst\", \"timestamp\"])\n  |> aggregateWindow(every: inf, fn: sum)\n  |> drop(columns: [\"_time\", \"_start\", \"_stop\"])\n  |> filter(fn: (r) => r[\"_value\"] != 0)\n  |> group()\n\n  |> map(fn: (r) => ({ r with src: if r.src == \"2a04:f340::a\" then \"h01\" else r.src }))\n  |> map(fn: (r) => ({ r with dst: if r.dst == \"2a04:f340::a\" then \"h01\" else r.dst }))\n\n  |> map(fn: (r) => ({ r with src: if r.src == \"2a00:10c0::a\" then \"h02\" else r.src }))\n  |> map(fn: (r) => ({ r with dst: if r.dst == \"2a00:10c0::a\" then \"h02\" else r.dst }))\n\n  |> map(fn: (r) => ({ r with src: if r.src == \"2001:67c:470::a\" then \"h03\" else r.src }))\n  |> map(fn: (r) => ({ r with dst: if r.dst == \"2001:67c:470::a\" then \"h03\" else r.dst }))\n\n  |> map(fn: (r) => ({ r with src: if r.src == \"2a00:c38::a\" then \"h04\" else r.src }))\n  |> map(fn: (r) => ({ r with dst: if r.dst == \"2a00:c38::a\" then \"h04\" else r.dst }))\n\n  |> map(fn: (r) => ({ r with src: if r.src == \"2a02:2d8::a\" then \"h05\" else r.src }))\n  |> map(fn: (r) => ({ r with dst: if r.dst == \"2a02:2d8::a\" then \"h05\" else r.dst }))\n\n  |> map(fn: (r) => ({ r with src: if r.src == \"2607:5d00::a\" then \"h06\" else r.src }))\n  |> map(fn: (r) => ({ r with dst: if r.dst == \"2607:5d00::a\" then \"h06\" else r.dst }))\n\n  |> map(fn: (r) => ({ r with src: if r.src == \"2a05:ff80::a\" then \"h07\" else r.src }))\n  |> map(fn: (r) => ({ r with dst: if r.dst == \"2a05:ff80::a\" then \"h07\" else r.dst }))\n\n  |> map(fn: (r) => ({ r with src: if r.src == \"2a0a:de00::a\" then \"h08\" else r.src }))\n  |> map(fn: (r) => ({ r with dst: if r.dst == \"2a0a:de00::a\" then \"h08\" else r.dst }))\n\n  |> map(fn: (r) => ({ r with src: if r.src == \"2001:678:274::a\" then \"h09\" else r.src }))\n  |> map(fn: (r) => ({ r with dst: if r.dst == \"2001:678:274::a\" then \"h09\" else r.dst }))\n\n  |> map(fn: (r) => ({ r with src: if r.src == \"2001:678:e0::a\" then \"h10\" else r.src }))\n  |> map(fn: (r) => ({ r with dst: if r.dst == \"2001:678:e0::a\" then \"h10\" else r.dst }))\n\n  |> map(fn: (r) => ({ r with src: if r.src == \"2001:678:7f0::a\" then \"h11\" else r.src }))\n  |> map(fn: (r) => ({ r with dst: if r.dst == \"2001:678:7f0::a\" then \"h11\" else r.dst }))"
    }
   ]
  },
  {
   "title": "Number of Packets with Unsupported Namespace",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 41 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"aggregated_data_export\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"netflow\")\n  |> filter(fn: (r) => r[\"type_5055\"] != \"0\")\n  |> filter(fn: (r) => r[\"_field\"] == \"type_5051\")\n  |> keep(columns: [\"_time\", \"flow_label\", \"type_5052\", \"type_5055\"])\n  |> group(columns: [\"flow_label\", \"src\", \"dst\"])\n  |> map(fn: (r) => ({ r with _value: int(v: r.type_5055) }))\n  |> aggregateWindow(every: inf, fn: sum)\n  |> drop(columns: [\"flow_label\"])\n  |> aggregateWindow(every: inf, fn: sum)\n  |> filter(fn: (r) => r[\"_value\"] != 0)"
    }
   ]
  },
  {
   "title": "Number of Packets per Flow with Unsupported Namespace",
   "type": "table",
   "gridPos": { "h": 7, "w": 17, "x": 7, "y": 41 },
   "targets": [
    {
     "query": "from(bucket: \"aggregated_data_export\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"netflow\")\n  |> filter(fn: (r) => r[\"type_5055\"] != \"0\")\n  |> filter(fn: (r) => r[\"_field\"] == \"type_5051\")\n  |> keep(columns: [\"_time\", \"flow_label\", \"src\", \"dst\", \"type_5052\", \"type_5055\"])\n  |> map(fn: (r) => ({ r with _value: int(v: r.type_5055) }))\n  |> group(columns: [\"flow_label\"])\n  |> truncateTimeColumn(unit: 1s)\n  |> map(fn: (r) => ({ r with timestamp: r._time }))\n  |> group(columns: [\"flow_label\", \"src\", \"dst\", \"timestamp\"])\n  |> aggregateWindow(every: inf, fn: sum)\n  |> drop(columns: [\"_time\", \"_start\", \"_stop\"])\n  |> filter(fn: (r) => r[\"_value\"] != 0)\n  |> group()\n\n  |> map(fn: (r) => ({ r with src: if r.src == \"2a04:f340::a\" then \"h01\" else r.src }))\n  |> map(fn: (r) => ({ r with dst: if r.dst == \"2a04:f340::a\" then \"h01\" else r.dst }))\n\n  |> map(fn: (r) => ({ r with src: if r.src == \"2a00:10c0::a\" then \"h02\" else r.src }))\n  |> map(fn: (r) => ({ r with dst: if r.dst == \"2a00:10c0::a\" then \"h02\" else r.dst }))\n\n  |> map(fn: (r) => ({ r with src: if r.src == \"2001:67c:470::a\" then \"h03\" else r.src }))\n  |> map(fn: (r) => ({ r with dst: if r.dst == \"2001:67c:470::a\" then \"h03\" else r.dst }))\n\n  |> map(fn: (r) => ({ r with src: if r.src == \"2a00:c38::a\" then \"h04\" else r.src }))\n  |> map(fn: (r) => ({ r with dst: if r.dst == \"2a00:c38::a\" then \"h04\" else r.dst }))\n\n  |> map(fn: (r) => ({ r with src: if r.src == \"2a02:2d8::a\" then \"h05\" else r.src }))\n  |> map(fn: (r) => ({ r with dst: if r.dst == \"2a02:2d8::a\" then \"h05\" else r.dst }))\n\n  |> map(fn: (r) => ({ r with src: if r.src == \"2607:5d00::a\" then \"h06\" else r.src }))\n  |> map(fn: (r) => ({ r with dst: if r.dst == \"2607:5d00::a\" then \"h06\" else r.dst }))\n\n  |> map(fn: (r) => ({ r with src: if r.src == \"2a05:ff80::a\" then \"h07\" else r.src }))\n  |> map(fn: (r) => ({ r with dst: if r.dst == \"2a05:ff80::a\" then \"h07\" else r.dst }))\n\n  |> map(fn: (r) => ({ r with src: if r.src == \"2a0a:de00::a\" then \"h08\" else r.src }))\n  |> map(fn: (r) => ({ r with dst: if r.dst == \"2a0a:de00::a\" then \"h08\" else r.dst }))\n\n  |> map(fn: (r) => ({ r with src: if r.src == \"2001:678:274::a\" then \"h09\" else r.src }))\n  |> map(fn: (r) => ({ r with dst: if r.dst == \"2001:678:274::a\" then \"h09\" else r.dst }))\n\n  |> map(fn: (r) => ({ r with src: if r.src == \"2001:678:e0::a\" then \"h10\" else r.src }))\n  |> map(fn: (r) => ({ r with dst: if r.dst == \"2001:678:e0::a\" then \"h10\" else r.dst }))\n\n  |> map(fn: (r) => ({ r with src: if r.src == \"2001:678:7f0::a\" then \"h11\" else r.src }))\n  |> map(fn: (r) => ({ r with dst: if r.dst == \"2001:678:7f0::a\" then \"h11\" else r.dst }))"
    }
   ]
  },
  {
   "title": "Number of Packets with Other Errors",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"aggregated_data_export\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"netflow\")\n  |> filter(fn: (r) => r[\"type_5056\"] != \"0\")\n  |> filter(fn: (r) => r[\"_field\"] == \"type_5051\")\n  |> keep(columns: [\"_time\", \"flow_label\", \"type_5052\", \"type_5056\"])\n  |> group(columns: [\"flow_label\", \"src\", \"dst\"])\n  |> map(fn: (r) => ({ r with _value: int(v: r.type_5056) }))\n  |> aggregateWindow(every: inf, fn: sum)\n  |> drop(columns: [\"flow_label\"])\n  |> aggregateWindow(every: inf, fn: sum)\n  |> filter(fn: (r) => r[\"_value\"] != 0)"
    }
   ]
  },
  {
   "title": "Number of Packet per Flow with Other Errors",
   "type": "table",
   "gridPos": { "h": 7, "w": 17, "x": 7, "y": 48 },
   "targets": [
    {
     "query": "from(bucket: \"aggregated_data_export\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"netflow\")\n  |> filter(fn: (r) => r[\"type_5056\"] != \"0\")\n  |> filter(fn: (r) => r[\"_field\"] == \"type_5051\")\n  |> keep(columns: [\"_time\", \"flow_label\", \"src\", \"dst\", \"type_5052\", \"type_5056\"])\n  |> map(fn: (r) => ({ r with _value: int(v: r.type_5056) }))\n  |> group(columns: [\"flow_label\"])\n  |> truncateTimeColumn(unit: 1s)\n  |> map(fn: (r) => ({ r with timestamp: r._time }))\n  |> group(columns: [\"flow_label\", \"src\", \"dst\", \"timestamp\"])\n  |> aggregateWindow(every: inf, fn: sum)\n  |> drop(columns: [\"_time\", \"_start\", \"_stop\"])\n  |> filter(fn: (r) => r[\"_value\"] != 0)\n  |> group()\n\n  |> map(fn: (r) => ({ r with src: if r.src == \"2a04:f340::a\" then \"h01\" else r.src }))\n  |> map(fn: (r) => ({ r with dst: if r.dst == \"2a04:f340::a\" then \"h01\" else r.dst }))\n\n  |> map(fn: (r) => ({ r with src: if r.src == \"2a00:10c0::a\" then \"h02\" else r.src }))\n  |> map(fn: (r) => ({ r with dst: if r.dst == \"2a00:10c0::a\" then \"h02\" else r.dst }))\n\n  |> map(fn: (r) => ({ r with src: if r.src == \"2001:67c:470::a\" then \"h03\" else r.src }))\n  |> map(fn: (r) => ({ r with dst: if r.dst == \"2001:67c:470::a\" then \"h03\" else r.dst }))\n\n  |> map(fn: (r) => ({ r with src: if r.src == \"2a00:c38::a\" then \"h04\" else r.src }))\n  |> map(fn: (r) => ({ r with dst: if r.dst == \"2a00:c38::a\" then \"h04\" else r.dst }))\n\n  |> map(fn: (r) => ({ r with src: if r.src == \"2a02:2d8::a\" then \"h05\" else r.src }))\n  |> map(fn: (r) => ({ r with dst: if r.dst == \"2a02:2d8::a\" then \"h05\" else r.dst }))\n\n  |> map(fn: (r) => ({ r with src: if r.src == \"2607:5d00::a\" then \"h06\" else r.src }))\n  |> map(fn: (r) => ({ r with dst: if r.dst == \"2607:5d00::a\" then \"h06\" else r.dst }))\n\n  |> map(fn: (r) => ({ r with src: if r.src == \"2a05:ff80::a\" then \"h07\" else r.src }))\n  |> map(fn: (r) => ({ r with dst: if r.dst == \"2a05:ff80::a\" then \"h07\" else r.dst }))\n\n  |> map(fn: (r) => ({ r with src: if r.src == \"2a0a:de00::a\" then \"h08\" else r.src }))\n  |> map(fn: (r) => ({ r with dst: if r.dst == \"2a0a:de00::a\" then \"h08\" else r.dst }))\n\n  |> map(fn: (r) => ({ r with src: if r.src == \"2001:678:274::a\" then \"h09\" else r.src }))\n  |> map(fn: (r) => ({ r with dst: if r.dst == \"2001:678:274::a\" then \"h09\" else r.dst }))\n\n  |> map(fn: (r) => ({ r with src: if r.src == \"2001:678:e0::a\" then \"h10\" else r.src }))\n  |> map(fn: (r) => ({ r with dst: if r.dst == \"2001:678:e0::a\" then \"h10\" else r.dst }))\n\n  |> map(fn: (r) => ({ r with src: if r.src == \"2001:678:7f0::a\" then \"h11\" else r.src }))\n  |> map(fn: (r) => ({ r with dst: if r.dst == \"2001:678:7f0::a\" then \"h11\" else r.dst }))"
    }
   ]
  },
  {
   "title": "Flow Error Overview",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 55 },
   "targets": [
    {
     "query": "from(bucket: \"raw_data_export\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"netflow\")\n  |> filter(fn: (r) => r[\"flags\"] != \"0\")\n  |> filter(fn: (r) => r[\"_field\"] == \"aggregate\")\n  |> group(columns: [\"flow_label\", \"source_ipv6\", \"destination_ipv6\"])\n  |> map(fn: (r) => ({ r with path: r.node_01 + \"-\" + r.node_02 + \"-\" + r.node_03 + \"-\" + r.node_04}))\n  |> keep(columns: [\"_time\", \"flow_label\", \"source_ipv6\", \"destination_ipv6\", \"flags\", \"aggregator\", \"auxil_data_node_id\", \"namespace_id\", \"path\"])\n  |> group()\n\n  |> map(fn: (r) => ({ r with source_ipv6: if r.source_ipv6 == \"2a04:f340:0000:0000:0000:0000:0000:000a\" then \"h01\" else r.source_ipv6 }))\n  |> map(fn: (r) => ({ r with destination_ipv6: if r.destination_ipv6 == \"2a04:f340:0000:0000:0000:0000:0000:000a\" then \"h01\" else r.destination_ipv6 }))\n\n  |> map(fn: (r) => ({ r with source_ipv6: if r.source_ipv6 == \"2a00:10c0:0000:0000:0000:0000:0000:000a\" then \"h02\" else r.source_ipv6 }))\n  |> map(fn: (r) => ({ r with destination_ipv6: if r.destination_ipv6 == \"2a00:10c0:0000:0000:0000:0000:0000:000a\" then \"h02\" else r.destination_ipv6 }))\n\n  |> map(fn: (r) => ({ r with source_ipv6: if r.source_ipv6 == \"2001:067c:0470:0000:0000:0000:0000:000a\" then \"h03\" else r.source_ipv6 }))\n  |> map(fn: (r) => ({ r with destination_ipv6: if r.destination_ipv6 == \"2001:067c:0470:0000:0000:0000:0000:000a\" then \"h03\" else r.destination_ipv6 }))\n\n  |> map(fn: (r) => ({ r with source_ipv6: if r.source_ipv6 == \"2a00:0c38:0000:0000:0000:0000:0000:000a\" then \"h04\" else r.source_ipv6 }))\n  |> map(fn: (r) => ({ r with destination_ipv6: if r.destination_ipv6 == \"2a00:0c38:0000:0000:0000:0000:0000:000a\" then \"h04\" else r.destination_ipv6 }))\n\n  |> map(fn: (r) => ({ r with source_ipv6: if r.source_ipv6 == \"2a02:02d8:0000:0000:0000:0000:0000:000a\" then \"h05\" else r.source_ipv6 }))\n  |> map(fn: (r) => ({ r with destination_ipv6: if r.destination_ipv6 == \"2a02:02d8:0000:0000:0000:0000:0000:000a\" then \"h05\" else r.destination_ipv6 }))\n\n  |> map(fn: (r) => ({ r with source_ipv6: if r.source_ipv6 == \"2607:5d00:0000:0000:0000:0000:0000:000a\" then \"h06\" else r.source_ipv6 }))\n  |> map(fn: (r) => ({ r with destination_ipv6: if r.destination_ipv6 == \"2607:5d00:0000:0000:0000:0000:0000:000a\" then \"h06\" else r.destination_ipv6 }))\n\n  |> map(fn: (r) => ({ r with source_ipv6: if r.source_ipv6 == \"2a05:ff80:0000:0000:0000:0000:0000:000a\" then \"h07\" else r.source_ipv6 }))\n  |> map(fn: (r) => ({ r with destination_ipv6: if r.destination_ipv6 == \"2a05:ff80:0000:0000:0000:0000:0000:000a\" then \"h07\" else r.destination_ipv6 }))\n\n  |> map(fn: (r) => ({ r with source_ipv6: if r.source_ipv6 == \"2a0a:de00:0000:0000:0000:0000:0000:000a\" then \"h08\" else r.source_ipv6 }))\n  |> map(fn: (r) => ({ r with destination_ipv6: if r.destination_ipv6 == \"2a0a:de00:0000:0000:0000:0000:0000:000a\" then \"h08\" else r.destination_ipv6 }))\n\n  |> map(fn: (r) => ({ r with source_ipv6: if r.source_ipv6 == \"2001:0678:0274:0000:0000:0000:0000:000a\" then \"h09\" else r.source_ipv6 }))\n  |> map(fn: (r) => ({ r with destination_ipv6: if r.destination_ipv6 == \"2001:0678:0274:0000:0000:0000:0000:000a\" then \"h09\" else r.destination_ipv6 }))\n\n  |> map(fn: (r) => ({ r with source_ipv6: if r.source_ipv6 == \"2001:0678:00e0:0000:0000:0000:0000:000a\" then \"h10\" else r.source_ipv6 }))\n  |> map(fn: (r) => ({ r with destination_ipv6: if r.destination_ipv6 == \"2001:0678:00e0:0000:0000:0000:0000:000a\" then \"h10\" else r.destination_ipv6 }))\n\n  |> map(fn: (r) => ({ r with source_ipv6: if r.source_ipv6 == \"2001:0678:07f0:0000:0000:0000:0000:000a\" then \"h11\" else r.source_ipv6 }))\n  |> map(fn: (r) => ({ r with destination_ipv6: if r.destination_ipv6 == \"2001:0678:07f0:0000:0000:0000:0000:000a\" then \"h11\" else r.destination_ipv6 }))"
    }
   ]
  }
 ]
}