bmv2_json: network/p4/build/main.json
hosts:
  h01:
    commands:
    - route add default gw 146.185.64.1 dev eth0
    - arp -i eth0 -s 146.185.64.1 08:EE:00:00:00:11
    - python3 network/utils/traffic_generator.py --ipv6 --src 'h01' --infinite --startup-delay
      15 --pcap-file network/utils/captures/quic_ipv6.pcapng --log-dir config/logs
      --config config/generator/out/traffic-generator-config.json &
    ipv4:
      ip: 146.185.64.10
      net: 146.185.64.0
      prefix_len: 19
    ipv6:
      ip: 2a04:f340::a
      net: '2a04:f340::'
      prefix_len: 29
    mac: 08:FF:00:00:00:01
  h02:
    commands:
    - route add default gw 31.24.8.1 dev eth0
    - arp -i eth0 -s 31.24.8.1 08:EE:00:00:00:12
    - python3 network/utils/traffic_generator.py --ipv6 --src 'h02' --infinite --startup-delay
      15 --pcap-file network/utils/captures/quic_ipv6.pcapng --log-dir config/logs
      --config config/generator/out/traffic-generator-config.json &
    ipv4:
      ip: 31.24.8.10
      net: 31.24.8.0
      prefix_len: 21
    ipv6:
      ip: 2a00:10c0::a
      net: '2a00:10c0::'
      prefix_len: 32
    mac: 08:FF:00:00:00:02
  h03:
    commands:
    - route add default gw 31.207.52.1 dev eth0
    - arp -i eth0 -s 31.207.52.1 08:EE:00:00:00:12
    - python3 network/utils/traffic_generator.py --ipv6 --src 'h03' --infinite --startup-delay
      15 --pcap-file network/utils/captures/quic_ipv6.pcapng --log-dir config/logs
      --config config/generator/out/traffic-generator-config.json &
    ipv4:
      ip: 31.207.52.10
      net: 31.207.52.0
      prefix_len: 22
    ipv6:
      ip: 2001:67c:470::a
      net: '2001:67c:470::'
      prefix_len: 48
    mac: 08:FF:00:00:00:03
  h04:
    commands:
    - route add default gw 31.132.8.1 dev eth0
    - arp -i eth0 -s 31.132.8.1 08:EE:00:00:00:13
    - python3 network/utils/traffic_generator.py --ipv6 --src 'h04' --infinite --startup-delay
      15 --pcap-file network/utils/captures/quic_ipv6.pcapng --log-dir config/logs
      --config config/generator/out/traffic-generator-config.json &
    ipv4:
      ip: 31.132.8.10
      net: 31.132.8.0
      prefix_len: 22
    ipv6:
      ip: 2a00:c38::a
      net: '2a00:c38::'
      prefix_len: 32
    mac: 08:FF:00:00:00:04
  h05:
    commands:
    - route add default gw 23.56.98.1 dev eth0
    - arp -i eth0 -s 23.56.98.1 08:EE:00:00:00:13
    - python3 network/utils/traffic_generator.py --ipv6 --src 'h05' --infinite --startup-delay
      15 --pcap-file network/utils/captures/quic_ipv6.pcapng --log-dir config/logs
      --config config/generator/out/traffic-generator-config.json &
    ipv4:
      ip: 23.56.98.10
      net: 23.56.98.0
      prefix_len: 24
    ipv6:
      ip: 2a02:2d8::a
      net: '2a02:2d8::'
      prefix_len: 32
    mac: 08:FF:00:00:00:05
  h06:
    commands:
    - route add default gw 45.61.192.1 dev eth0
    - arp -i eth0 -s 45.61.192.1 08:EE:00:00:00:14
    - python3 network/utils/traffic_generator.py --ipv6 --src 'h06' --infinite --startup-delay
      15 --pcap-file network/utils/captures/quic_ipv6.pcapng --log-dir config/logs
      --config config/generator/out/traffic-generator-config.json &
    ipv4:
      ip: 45.61.192.10
      net: 45.61.192.0
      prefix_len: 21
    ipv6:
      ip: 2607:5d00::a
      net: '2607:5d00::'
      prefix_len: 48
    mac: 08:FF:00:00:00:06
  h07:
    commands:
    - route add default gw 37.46.144.1 dev eth0
    - arp -i eth0 -s 37.46.144.1 08:EE:00:00:00:15
    - python3 network/utils/traffic_generator.py --ipv6 --src 'h07' --infinite --startup-delay
      15 --pcap-file network/utils/captures/quic_ipv6.pcapng --log-dir config/logs
      --config config/generator/out/traffic-generator-config.json &
    ipv4:
      ip: 37.46.144.10
      net: 37.46.144.0
      prefix_len: 22
    ipv6:
      ip: 2a05:ff80::a
      net: '2a05:ff80::'
      prefix_len: 29
    mac: 08:FF:00:00:00:07
  h08:
    commands:
    - route add default gw 31.207.60.1 dev eth0
    - arp -i eth0 -s 31.207.60.1 08:EE:00:00:00:16
    - python3 network/utils/traffic_generator.py --ipv6 --src 'h08' --infinite --startup-delay
      15 --pcap-file network/utils/captures/quic_ipv6.pcapng --log-dir config/logs
      --config config/generator/out/traffic-generator-config.json &
    ipv4:
      ip: 31.207.60.10
      net: 31.207.60.0
      prefix_len: 22
    ipv6:
      ip: 2a0a:de00::a
      net: '2a0a:de00::'
      prefix_len: 29
    mac: 08:FF:00:00:00:08
  h09:
    commands:
    - route add default gw 37.1.224.1 dev eth0
    - arp -i eth0 -s 37.1.224.1 08:EE:00:00:00:17
    - python3 network/utils/traffic_generator.py --ipv6 --src 'h09' --infinite --startup-delay
      15 --pcap-file network/utils/captures/quic_ipv6.pcapng --log-dir config/logs
      --config config/generator/out/traffic-generator-config.json &
    ipv4:
      ip: 37.1.224.10
      net: 37.1.224.0
      prefix_len: 22
    ipv6:
      ip: 2001:678:274::a
      net: '2001:678:274::'
      prefix_len: 48
    mac: 08:FF:00:00:00:09
  h10:
    commands:
    - route add default gw 46.14.0.1 dev eth0
    - arp -i eth0 -s 46.14.0.1 08:EE:00:00:00:17
    - python3 network/utils/traffic_generator.py --ipv6 --src 'h10' --infinite --startup-delay
      15 --pcap-file network/utils/captures/quic_ipv6.pcapng --log-dir config/logs
      --config config/generator/out/traffic-generator-config.json &
    ipv4:
      ip: 46.14.0.10
      net: 46.14.0.0
      prefix_len: 16
    ipv6:
      ip: 2001:678:e0::a
      net: '2001:678:e0::'
      prefix_len: 48
    mac: 08:FF:00:00:00:10
  h11:
    commands:
    - route add default gw 31.10.128.1 dev eth0
    - arp -i eth0 -s 31.10.128.1 08:EE:00:00:00:18
    - python3 network/utils/traffic_generator.py --ipv6 --src 'h11' --infinite --startup-delay
      15 --pcap-file network/utils/captures/quic_ipv6.pcapng --log-dir config/logs
      --config config/generator/out/traffic-generator-config.json &
    ipv4:
      ip: 31.10.128.10
      net: 31.10.128.0
      prefix_len: 24
    ipv6:
      ip: 2001:678:7f0::a
      net: '2001:678:7f0::'
      prefix_len: 48
    mac: 08:FF:00:00:00:11
p4info: network/p4/build/main.p4.p4info.txt
paths:
- egress: s12
  ingress: s11
  symmetric: false
  via:
  - s2
- egress: s13
  ingress: s11
  symmetric: false
  via:
  - s1
  - s3
- egress: s14
  ingress: s11
  symmetric: false
  via:
  - s2
- egress: s15
  ingress: s11
  symmetric: false
  via:
  - s1
  - s4
- egress: s16
  ingress: s11
  symmetric: false
  via:
  - s2
  - s3
- egress: s17
  ingress: s11
  symmetric: false
  via:
  - s1
- egress: s18
  ingress: s11
  symmetric: false
  via:
  - s2
  - s4
- egress: s12
  ingress: s12
  symmetric: false
  via: []
- egress: s13
  ingress: s12
  symmetric: false
  via:
  - s2
- egress: s14
  ingress: s12
  symmetric: false
  via:
  - s2
- egress: s15
  ingress: s12
  symmetric: false
  via:
  - s2
  - s3
- egress: s16
  ingress: s12
  symmetric: false
  via:
  - s1
  - s4
- egress: s17
  ingress: s12
  symmetric: false
  via:
  - s1
- egress: s18
  ingress: s12
  symmetric: false
  via:
  - s1
- egress: s13
  ingress: s13
  symmetric: false
  via: []
- egress: s14
  ingress: s13
  symmetric: false
  via:
  - s2
- egress: s15
  ingress: s13
  symmetric: false
  via:
  - s3
- egress: s16
  ingress: s13
  symmetric: false
  via:
  - s3
- egress: s17
  ingress: s13
  symmetric: false
  via:
  - s2
  - s1
- egress: s18
  ingress: s13
  symmetric: false
  via:
  - s2
  - s4
- egress: s15
  ingress: s14
  symmetric: false
  via:
  - s3
- egress: s16
  ingress: s14
  symmetric: false
  via:
  - s3
- egress: s17
  ingress: s14
  symmetric: false
  via:
  - s3
  - s4
- egress: s18
  ingress: s14
  symmetric: false
  via:
  - s3
  - s4
- egress: s16
  ingress: s15
  symmetric: false
  via:
  - s4
- egress: s17
  ingress: s15
  symmetric: false
  via:
  - s4
- egress: s18
  ingress: s15
  symmetric: false
  via:
  - s3
  - s4
- egress: s17
  ingress: s16
  symmetric: false
  via:
  - s3
  - s4
- egress: s18
  ingress: s16
  symmetric: false
  via:
  - s4
- egress: s17
  ingress: s17
  symmetric: false
  via: []
- egress: s18
  ingress: s17
  symmetric: false
  via:
  - s4
- egress: s11
  ingress: s12
  symmetric: false
  via:
  - s1
- egress: s11
  ingress: s13
  symmetric: false
  via:
  - s2
- egress: s11
  ingress: s14
  symmetric: false
  via:
  - s3
  - s1
- egress: s11
  ingress: s15
  symmetric: false
  via:
  - s3
  - s1
- egress: s11
  ingress: s16
  symmetric: false
  via:
  - s3
  - s1
- egress: s11
  ingress: s17
  symmetric: false
  via:
  - s4
  - s2
- egress: s11
  ingress: s18
  symmetric: false
  via:
  - s1
- egress: s12
  ingress: s13
  symmetric: false
  via:
  - s2
- egress: s12
  ingress: s14
  symmetric: false
  via:
  - s2
- egress: s12
  ingress: s15
  symmetric: false
  via:
  - s4
  - s1
- egress: s12
  ingress: s16
  symmetric: false
  via:
  - s3
  - s2
- egress: s12
  ingress: s17
  symmetric: false
  via:
  - s1
- egress: s12
  ingress: s18
  symmetric: false
  via:
  - s4
  - s1
- egress: s13
  ingress: s14
  symmetric: false
  via:
  - s2
- egress: s13
  ingress: s15
  symmetric: false
  via:
  - s3
- egress: s13
  ingress: s16
  symmetric: false
  via:
  - s3
- egress: s13
  ingress: s17
  symmetric: false
  via:
  - s1
  - s3
- egress: s13
  ingress: s18
  symmetric: false
  via:
  - s1
  - s3
- egress: s14
  ingress: s15
  symmetric: false
  via:
  - s3
- egress: s14
  ingress: s16
  symmetric: false
  via:
  - s3
- egress: s14
  ingress: s17
  symmetric: false
  via:
  - s1
  - s2
- egress: s14
  ingress: s18
  symmetric: false
  via:
  - s4
  - s3
- egress: s15
  ingress: s16
  symmetric: false
  via:
  - s4
- egress: s15
  ingress: s17
  symmetric: false
  via:
  - s4
- egress: s15
  ingress: s18
  symmetric: false
  via:
  - s1
  - s4
- egress: s16
  ingress: s17
  symmetric: false
  via:
  - s4
- egress: s16
  ingress: s18
  symmetric: false
  via:
  - s4
- egress: s17
  ingress: s18
  symmetric: false
  via:
  - s1
switches:
  s1:
    hei:
    - data_param: 255
      value: 10000
    ioam:
      aggregators:
      - 1
      - 2
      - 1
      - 4
      data_param: 255
      namespace_id: 10
      node_id: 1
    mac: 08:CC:00:00:00:01
    ports:
      1:
        lei: 250
        neighbor: s2
      2:
        lei: 500
        neighbor: s3
      3:
        lei: 100
        neighbor: s4
      4:
        lei: 200
        neighbor: s17
      5:
        lei: 200
        neighbor: s18
      6:
        lei: 200
        neighbor: s11
      7:
        lei: 200
        neighbor: s12
  s11:
    hei:
    - data_param: 255
      value: 11000
    ioam:
      aggregators:
      - 1
      - 2
      - 1
      - 4
      data_param: 255
      namespace_id: 10
      node_id: 11
    mac: 08:EE:00:00:00:11
    ports:
      1:
        lei: 200
        neighbor: s1
      2:
        lei: 200
        neighbor: s2
      3:
        lei: 100
        neighbor: h01
  s12:
    hei:
    - data_param: 255
      value: 12000
    ioam:
      aggregators:
      - 1
      - 2
      - 1
      - 4
      data_param: 255
      namespace_id: 10
      node_id: 12
    mac: 08:EE:00:00:00:12
    ports:
      1:
        lei: 200
        neighbor: s1
      2:
        lei: 200
        neighbor: s2
      3:
        lei: 100
        neighbor: h02
      4:
        lei: 100
        neighbor: h03
  s13:
    hei:
    - data_param: 255
      value: 13000
    ioam:
      aggregators:
      - 1
      - 2
      - 1
      - 4
      data_param: 255
      namespace_id: 10
      node_id: 13
    mac: 08:EE:00:00:00:13
    ports:
      1:
        lei: 200
        neighbor: s2
      2:
        lei: 200
        neighbor: s3
      3:
        lei: 100
        neighbor: h05
      4:
        lei: 100
        neighbor: h04
  s14:
    hei:
    - data_param: 255
      value: 24000
    ioam:
      aggregators:
      - 1
      - 2
      - 1
      - 4
      data_param: 255
      namespace_id: 10
      node_id: 14
    mac: 08:EE:00:00:00:14
    ports:
      1:
        lei: 200
        neighbor: s2
      2:
        lei: 200
        neighbor: s3
      3:
        lei: 100
        neighbor: h06
  s15:
    hei:
    - data_param: 255
      value: 25000
    ioam:
      aggregators:
      - 1
      - 2
      - 1
      - 4
      data_param: 255
      namespace_id: 10
      node_id: 15
    mac: 08:EE:00:00:00:15
    ports:
      1:
        lei: 200
        neighbor: s4
      2:
        lei: 200
        neighbor: s3
      3:
        lei: 100
        neighbor: h07
  s16:
    hei:
    - data_param: 255
      value: 26000
    ioam:
      aggregators:
      - 1
      - 2
      - 1
      - 4
      data_param: 255
      namespace_id: 10
      node_id: 16
    mac: 08:EE:00:00:00:16
    ports:
      1:
        lei: 200
        neighbor: s4
      2:
        lei: 200
        neighbor: s3
      3:
        lei: 100
        neighbor: h08
  s17:
    hei:
    - data_param: 255
      value: 17000
    ioam:
      aggregators:
      - 1
      - 2
      - 1
      - 4
      data_param: 255
      namespace_id: 10
      node_id: 17
    mac: 08:EE:00:00:00:17
    ports:
      1:
        lei: 200
        neighbor: s1
      2:
        lei: 200
        neighbor: s4
      3:
        lei: 100
        neighbor: h09
      4:
        lei: 100
        neighbor: h10
  s18:
    hei:
    - data_param: 255
      value: 1
    ioam:
      aggregators:
      - 1
      - 2
      - 1
      - 4
      data_param: 255
      namespace_id: 10
      node_id: 18
    mac: 08:EE:00:00:00:18
    ports:
      1:
        lei: 200
        neighbor: s1
      2:
        lei: 200
        neighbor: s4
      3:
        lei: 100
        neighbor: h11
  s2:
    hei:
    - data_param: 255
      value: 25000
    ioam:
      aggregators:
      - 1
      - 2
      - 1
      - 4
      data_param: 255
      namespace_id: 10
      node_id: 2
    mac: 08:CC:00:00:00:02
    ports:
      1:
        lei: 250
        neighbor: s1
      2:
        lei: 500
        neighbor: s4
      3:
        lei: 100
        neighbor: s3
      4:
        lei: 200
        neighbor: s14
      5:
        lei: 200
        neighbor: s13
      6:
        lei: 200
        neighbor: s12
      7:
        lei: 200
        neighbor: s11
  s3:
    hei:
    - data_param: 255
      value: 60000
    ioam:
      aggregators:
      - 1
      - 2
      - 1
      - 4
      data_param: 255
      namespace_id: 10
      node_id: 3
    mac: 08:CC:00:00:00:03
    ports:
      1:
        lei: 100
        neighbor: s2
      2:
        lei: 500
        neighbor: s1
      3:
        lei: 250
        neighbor: s4
      4:
        lei: 200
        neighbor: s16
      5:
        lei: 200
        neighbor: s15
      6:
        lei: 200
        neighbor: s14
      7:
        lei: 200
        neighbor: s13
  s4:
    hei:
    - data_param: 255
      value: 20000
    ioam:
      aggregators:
      - 1
      - 2
      - 1
      - 4
      data_param: 255
      namespace_id: 10
      node_id: 4
    mac: 08:CC:00:00:00:04
    ports:
      1:
        lei: 100
        neighbor: s1
      2:
        lei: 500
        neighbor: s2
      3:
        lei: 250
        neighbor: s3
      4:
        lei: 200
        neighbor: s15
      5:
        lei: 200
        neighbor: s16
      6:
        lei: 200
        neighbor: s17
      7:
        lei: 200
        neighbor: s18
tables:
  egress_lei:
    action_name: MyEgress.process_efficiency_indicator.add_indicator_to_aggregate
    default_action: MyEgress.process_efficiency_indicator.indicate_other_error
    match_key: standard_metadata.egress_port
    name: MyEgress.process_efficiency_indicator.get_egress_link_efficiency_indicator
  hei:
    action_name: MyEgress.process_efficiency_indicator.add_indicator_to_aggregate
    default_action: MyEgress.process_efficiency_indicator.indicate_data_param_error
    match_key: hdr.ioam_a_ioam_aggregation.dataParam
    name: MyEgress.process_efficiency_indicator.get_hop_efficiency_indicator
  ingress_lei:
    action_name: MyEgress.process_efficiency_indicator.add_indicator_to_aggregate
    default_action: MyEgress.process_efficiency_indicator.indicate_other_error
    match_key: standard_metadata.ingress_port
    name: MyEgress.process_efficiency_indicator.get_ingress_link_efficiency_indicator
  ioam_aggr_aggregator:
    action_name: MyEgress.process_ioam_init.ioam_aggr_set_aggregator
    default_action: MyEgress.process_ioam_init.ioam_aggr_fallback_default_aggregator
    match_key: meta.ioamAggrMeta.aggregator_selector
    name: MyEgress.process_ioam_init.ioam_aggr_aggregator
  ioam_aggr_data_param:
    action_name: MyEgress.process_ioam_init.ioam_aggr_get_data_param
    default_action: MyEgress.process_ioam_init.indicate_other_error
    match_key: hdr.ethernet.srcAddr
    name: MyEgress.process_ioam_init.ioam_aggr_data_param
  ioam_namespace_id:
    action_name: MyEgress.process_ioam_init.ioam_get_namespace_id
    default_action: MyEgress.process_ioam_init.indicate_other_error
    match_key: hdr.ethernet.srcAddr
    name: MyEgress.process_ioam_init.ioam_namespace_id
  ioam_node_id:
    action_name: MyEgress.process_ioam_init.ioam_get_node_id
    default_action: MyEgress.process_ioam_init.indicate_other_error
    match_key: hdr.ethernet.srcAddr
    name: MyEgress.process_ioam_init.ioam_node_id
  ipv4_forwarding:
    action_name: MyIngress.ipv4_forward
    default_action: MyIngress.drop
    match_key: hdr.ipv4.dstAddr
    name: MyIngress.ipv4_lpm
  ipv6_forwarding:
    action_name: MyIngress.ipv6_forward
    default_action: MyIngress.drop
    match_key: hdr.ipv6.dstAddr
    name: MyIngress.ipv6_lpm
  ipv6_reverse_lookup:
    action_name: MyEgress.process_ioam_init.set_reverse_route_type
    default_action: MyEgress.process_ioam_init.set_default_reverse_route_type
    match_key: hdr.ipv6.srcAddr
    name: MyEgress.process_ioam_init.ipv6_reverse_lookup
